medicine_vision_detector:
  ros__parameters:
    input_mode: camera
    camera_device: /dev/video21
    camera_width: 1280
    camera_height: 720
    camera_fps: 15
    camera_fourcc: MJPG
    camera_read_period_sec: 0.07
    enable_preview_server: true
    preview_host: 0.0.0.0
    preview_port: 8090
    preview_quality: 35
    preview_draw_overlay: true
    preview_stream_period_sec: 0.3
    preview_encode_period_sec: 0.3
    enable_qr_recognition: true
    enable_datamatrix_recognition: true
    enable_zxingcpp_recognition: true
    enable_pylibdmtx_recognition: false
    qr_recognition_period_sec: 1.0
    qr_fast_mode: true
    qr_scale_factor: 1.0
    qr_extra_scale_factors: "1.0"
    external_decoder_period_sec: 1.0
    external_decoder_timeout_sec: 0.8
    enable_isolated_zxingcpp_recognition: true
    enable_opencv_curved_qr_recognition: false
    enable_ocr_recognition: false
    enable_yolo_rknn_detection: true
    yolo_model_path: /mnt/sdcard/medicine_robot_data/models/yolov8n_rk3588.rknn
    yolo_input_size: 640
    yolo_detection_period_sec: 0.2
    yolo_confidence_threshold: 0.20
    yolo_nms_threshold: 0.45
    yolo_detections_topic: /medicine/vision_detections
    yolo_status_topic: /medicine/yolo_rknn_status
    yolo_rknn_core_mask: auto
    yolo_class_filter: person
    yolo_publish_empty_detections: false
    yolo_letterbox_pad_value: 0
    yolo_draw_overlay: true
